# Generated by Django 5.1.4 on 2025-11-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=20)),
                ('tela', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
