# Generated by Django 5.2.8 on 2025-11-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=20)),
                ('producto_color', models.CharField(max_length=20)),
                ('producto_metros', models.IntegerField()),
                ('producto_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(max_length=20)),
                ('proveedor_ciudad', models.CharField(max_length=20)),
                ('proveedor_telefono', models.IntegerField()),
            ],
        ),
    ]
