<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-11-11 15:01
=======
# Generated by Django 5.2.8 on 2025-11-12 02:33
>>>>>>> 0c1658b9099aa6ae43392d0bf5877bd3687095e0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=20)),
                ('producto_color', models.CharField(max_length=20)),
                ('producto_metros', models.IntegerField()),
<<<<<<< HEAD
=======
                ('producto_creacion', models.DateTimeField(auto_now_add=True)),
>>>>>>> 0c1658b9099aa6ae43392d0bf5877bd3687095e0
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
=======
                ('proveedor_nombre', models.CharField(max_length=20)),
                ('proveedor_ciudad', models.CharField(max_length=20)),
                ('proveedor_telefono', models.IntegerField()),
>>>>>>> 0c1658b9099aa6ae43392d0bf5877bd3687095e0
            ],
        ),
    ]
